import type { Metadata } from "next";
import { Inter, Nunito_Sans} from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito_sans = Nunito_Sans({
  subsets : ['latin'],
  weight : ['400', '500', '600', '700', '800'],
  display: 'swap'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="relative">
      <body className={`${nunito_sans.className} bg-[#0f172a] max-w-[80rem] mx-auto overflow-x-hidden`}>{children}</body>
    </html>
  );
}
